# Generated by Django 6.0 on 2025-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='another_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product'),
        ),
    ]
