# Generated by Django 6.0 on 2025-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products_another_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
