# Generated by Django 6.0 on 2025-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='another_product_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_img',
        ),
        migrations.AddField(
            model_name='products',
            name='another_product_img_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Additional Image URL'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Product Image URL'),
        ),
    ]
