# Generated by Django 6.0 on 2025-12-25 06:08

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_address_user_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=store.models.generate_order_id, editable=False, max_length=36, unique=True),
        ),
    ]
